admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: /home
    defaults: { _controller: AppBundle:Welcome:welcome}

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "change_password.xml"
    prefix: /profile

registration_requests_overview:
    path: /Suivie_de_mes_demandes
    defaults: { _controller: UserBundle:Profile:showRequests}

tvshows:
    path: /emissions
    defaults: { _controller: AppBundle:TVShow:showAll}

show_tvshow:
    path: /emissions/{id}
    defaults: { _controller: AppBundle:TVShow:show}

faq:
    path: /faq
    defaults: { _controller: AppBundle:Help:showFAQ}

contact:
    path: /contact
    defaults: { _controller: AppBundle:Help:showContact}

legal_notice:
    path: /mentions_legales
    defaults: { _controller: AppBundle:Help:showLegalNotice}
    
request_registration_form:
    path: /registration_request/{recordingID}/form
    defaults: { _controller: AppBundle:RegistrationRequest:generateForm}
    methods: [GET, POST]

calendar:
    path: /calendrier
    defaults: { _controller: AppBundle:Calendar:show}

about_us:
    path: /qui-sommes-nous
    defaults: { _controller: AppBundle:Help:showAboutUs}