root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /welcome
        permanent: true

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

welcome_page:
    path: /welcome
    defaults: { _controller: AppBundle:Welcome:welcome}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

