UserBundle\Entity\User:
    # Your custom fields in your user entity, here is an example with FirstName
    properties:
        firstName:
            - NotBlank:
                message: "Veuillez saisir votre prénom."
                groups: [ "UserRegistration" ]
        lastName:
            - NotBlank:
                message: "Veuillez saisir votre nom."
                groups: [ "UserRegistration" ]

        phoneNumber:
            - NotBlank:
                message: "Veuillez saisir un numéro de téléphone."
                groups: [ "UserRegistration" ]
            - Regex :
                pattern: "/^(\+)?([0-9]|-|\(|\)|\.|\\s){8,}$/"
                match: true
                message: "Le numéro de téléphone n'est pas valide."
                groups: [ "UserRegistration" ]
        gender:
            - NotBlank:
                message: "Veuillez selectionner votre genre."
                groups: [ "UserRegistration" ]
        address:
            - NotBlank:
                message: "Veuillez saisir votre adresse."
                groups: [ "UserRegistration" ]
        zipCode:
            - NotBlank:
                message: "Veuillez saisir votre code postal."
                groups: [ "UserRegistration" ]
        city:
            - NotBlank:
                message: "Veuillez saisir votre ville."
                groups: [ "UserRegistration" ]
        birthday:
            - NotBlank:
                message: "Veuillez saisir votre date de naissance."
                groups: [ "UserRegistration" ]

# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to 
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
             fields: email
             errorPath: email 
             message: fos_user.email.already_used
             groups: [ "UserRegistration", "UserProfile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "UserRegistration", "UserProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "UserRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "UserRegistration", "UserProfile", "ResetPassword" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "UserRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "UserRegistration", "UserProfile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "UserRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "UserRegistration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "UserRegistration", "UserProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "UserRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "UserRegistration", "UserProfile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "UserRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "UserRegistration", "UserProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "UserRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "UserRegistration" ]